name: attendance_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.7  # Replace with the actual latest stable version
  path_provider: ^2.0.12 # Replace with the actual latest stable version
  cupertino_icons: ^1.0.8
  http: ^1.1.0 # Replace with the actual latest stable version
  camera: ^0.11.1  # Add camera package for face scanning
  image_picker: ^1.1.2  # Add image picker package for face scanning
  qr_code_scanner_plus: ^2.0.10+1  # Add QR code scanner package
  logging: ^1.0.0
  permission_handler: ^10.2.0  # Add permission_handler package
  logger: ^1.0.0  # Add logger package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
